using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MovieTrackR.Infrastructure;

public static class ModelBuilderExtensions
{
    // Use sequentials GUIDs for primary keys (better db performances and index fragmentation)
    public static ModelBuilder UseSequentialGuids(this ModelBuilder b)
    {
        foreach (IMutableEntityType entityType in b.Model.GetEntityTypes())
        {
            IMutableKey? pk = entityType.FindPrimaryKey();
            if (pk is null || pk.Properties.Count != 1) continue;

            IMutableProperty? p = pk.Properties[0];
            if (p.ClrType != typeof(Guid)) continue;

            // If you want to search the primary key property by name
            // IMutableProperty? propertyId = entityType.FindProperty("Id");

            // proper way for postgreSQL, requires the "uuid-ossp" extension enabled in the database
            b.Entity(entityType.ClrType)
             .Property<Guid>("Id")
             .ValueGeneratedOnAdd()
             .HasDefaultValueSql("uuid_generate_v1mc()");

            // If you want to use it with other databases (e.g. SqlServer) WARNING: guid generated by application and not by the database
            //propertyId.SetValueGeneratorFactory((p, e) => new SequentialGuidValueGenerator());
        }
        return b;
    }

    // Convert DateTime/DateTime? => UTC 
    public static ModelBuilder UseUtcDateTimes(this ModelBuilder b)
    {
        ValueConverter<DateTime, DateTime> dtConv = new ValueConverter<DateTime, DateTime>(
            v => v.ToUniversalTime(),
            v => DateTime.SpecifyKind(v, DateTimeKind.Utc));

        ValueConverter<DateTime?, DateTime?> ndtConv = new ValueConverter<DateTime?, DateTime?>(
            v => v.HasValue ? v.Value.ToUniversalTime() : v,
            v => v.HasValue ? DateTime.SpecifyKind(v.Value, DateTimeKind.Utc) : v);

        foreach (IMutableEntityType entity in b.Model.GetEntityTypes())
            foreach (IMutableProperty p in entity.GetProperties())
            {
                if (p.ClrType == typeof(DateTime))
                    b.Entity(entity.ClrType).Property<DateTime>(p.Name).HasConversion(dtConv);
                else if (p.ClrType == typeof(DateTime?))
                    b.Entity(entity.ClrType).Property<DateTime?>(p.Name).HasConversion(ndtConv);
            }
        return b;
    }
}
