// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTrackR.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieTrackR.Infrastructure.Migrations
{
    [DbContext(typeof(MovieTrackRDbContext))]
    [Migration("20251210162747_AddVisibilityManagementReviewAndComments")]
    partial class AddVisibilityManagementReviewAndComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieTrackR.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v1mc()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_name");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_tmdb_id");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v1mc()");

                    b.Property<string>("BackdropPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("backdrop_path");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text")
                        .HasColumnName("original_title");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text")
                        .HasColumnName("poster_url");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Tagline")
                        .HasColumnType("text")
                        .HasColumnName("tagline");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("text")
                        .HasColumnName("trailer_url");

                    b.Property<double?>("VoteAverage")
                        .HasPrecision(3, 1)
                        .HasColumnType("double precision")
                        .HasColumnName("vote_average");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_movies");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_movies_created_at");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_movies_tmdb_id")
                        .HasFilter("\"TmdbId\" IS NOT NULL");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.MovieCast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v1mc()");

                    b.Property<string>("CharacterName")
                        .HasColumnType("text")
                        .HasColumnName("character_name");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<int?>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_movie_cast");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_movie_cast_movie_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_movie_cast_person_id");

                    b.HasIndex("MovieId", "PersonId")
                        .HasDatabaseName("ix_movie_cast_movie_id_person_id");

                    b.ToTable("movie_cast", null, t =>
                        {
                            t.HasCheckConstraint("CK_movie_cast_order_non_negative", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.MovieCrew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v1mc()");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_movie_crew");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_movie_crew_movie_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_movie_crew_person_id");

                    b.HasIndex("MovieId", "PersonId", "Department", "Job")
                        .IsUnique()
                        .HasDatabaseName("ix_movie_crew_movie_id_person_id_department_job");

                    b.ToTable("movie_crew", (string)null);
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.HasKey("MovieId", "GenreId")
                        .HasName("pk_movie_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_movie_genres_genre_id");

                    b.ToTable("movie_genres", (string)null);
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.MovieProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v1mc()");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ModerationNote")
                        .HasColumnType("text")
                        .HasColumnName("moderation_note");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("original_title");

                    b.Property<string>("Overview")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("overview");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("poster_url");

                    b.Property<Guid>("ProposedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_by_user_id");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_movie_proposals");

                    b.HasIndex("ProposedByUserId")
                        .HasDatabaseName("ix_movie_proposals_proposed_by_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_movie_proposals_status");

                    b.ToTable("movie_proposals", null, t =>
                        {
                            t.HasCheckConstraint("CK_movie_proposals_release_year", "release_year IS NULL OR (release_year >= 1888 AND release_year <= EXTRACT(YEAR FROM CURRENT_DATE)::int + 1)");
                        });
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v1mc()");

                    b.Property<string>("Biography")
                        .HasColumnType("text")
                        .HasColumnName("biography");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("date")
                        .HasColumnName("death_date");

                    b.Property<string>("KnownForDepartment")
                        .HasColumnType("text")
                        .HasColumnName("known_for_department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_people_tmdb_id");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v1mc()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<bool>("PubliclyVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("publicly_visible");

                    b.Property<float>("Rating")
                        .HasColumnType("real")
                        .HasColumnName("rating");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_reviews_movie_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user_id");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_user_id_movie_id");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_reviews_rating_range", "rating >= 0 AND rating <= 5");
                        });
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.ReviewComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v1mc()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("PubliclyVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("publicly_visible");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_review_comments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_review_comments_user_id");

                    b.HasIndex("ReviewId", "CreatedAt")
                        .HasDatabaseName("ix_review_comments_review_id_created_at");

                    b.ToTable("review_comments", (string)null);
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.ReviewLike", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ReviewId", "UserId")
                        .HasName("pk_review_likes");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_review_likes_review_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_review_likes_user_id");

                    b.ToTable("review_likes", (string)null);
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v1mc()");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("given_name");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pseudo");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.UserList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v1mc()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_lists");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_lists_user_id");

                    b.ToTable("user_lists", (string)null);
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.UserListMovie", b =>
                {
                    b.Property<Guid>("UserListId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_list_id");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("UserListId", "MovieId")
                        .HasName("pk_user_list_movies");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_user_list_movies_movie_id");

                    b.HasIndex("UserListId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_user_list_movies_user_list_id_position");

                    b.ToTable("user_list_movies", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_list_movies_position_gt_zero", "position > 0");
                        });
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.MovieCast", b =>
                {
                    b.HasOne("MovieTrackR.Domain.Entities.Movie", "Movie")
                        .WithMany("Cast")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_cast_movies_movie_id");

                    b.HasOne("MovieTrackR.Domain.Entities.Person", "Person")
                        .WithMany("CastRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_cast_people_person_id");

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.MovieCrew", b =>
                {
                    b.HasOne("MovieTrackR.Domain.Entities.Movie", "Movie")
                        .WithMany("Crew")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_crew_movies_movie_id");

                    b.HasOne("MovieTrackR.Domain.Entities.Person", "Person")
                        .WithMany("CrewRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_crew_people_person_id");

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.MovieGenre", b =>
                {
                    b.HasOne("MovieTrackR.Domain.Entities.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_genres_genre_id");

                    b.HasOne("MovieTrackR.Domain.Entities.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_movies_movie_id");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.MovieProposal", b =>
                {
                    b.HasOne("MovieTrackR.Domain.Entities.User", "ProposedByUser")
                        .WithMany()
                        .HasForeignKey("ProposedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_proposals_users_proposed_by_user_id");

                    b.Navigation("ProposedByUser");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.Review", b =>
                {
                    b.HasOne("MovieTrackR.Domain.Entities.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_movies_movie_id");

                    b.HasOne("MovieTrackR.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_user_id");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.ReviewComment", b =>
                {
                    b.HasOne("MovieTrackR.Domain.Entities.Review", "Review")
                        .WithMany("Comments")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_comments_reviews_review_id");

                    b.HasOne("MovieTrackR.Domain.Entities.User", "User")
                        .WithMany("ReviewComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_comments_users_user_id");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.ReviewLike", b =>
                {
                    b.HasOne("MovieTrackR.Domain.Entities.Review", "Review")
                        .WithMany("Likes")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_likes_reviews_review_id");

                    b.HasOne("MovieTrackR.Domain.Entities.User", "User")
                        .WithMany("ReviewLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_likes_users_user_id");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.UserList", b =>
                {
                    b.HasOne("MovieTrackR.Domain.Entities.User", "User")
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_lists_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.UserListMovie", b =>
                {
                    b.HasOne("MovieTrackR.Domain.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_list_movies_movies_movie_id");

                    b.HasOne("MovieTrackR.Domain.Entities.UserList", "UserList")
                        .WithMany("Movies")
                        .HasForeignKey("UserListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_list_movies_user_lists_user_list_id");

                    b.Navigation("Movie");

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.Movie", b =>
                {
                    b.Navigation("Cast");

                    b.Navigation("Crew");

                    b.Navigation("MovieGenres");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.Person", b =>
                {
                    b.Navigation("CastRoles");

                    b.Navigation("CrewRoles");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.Review", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.User", b =>
                {
                    b.Navigation("Lists");

                    b.Navigation("ReviewComments");

                    b.Navigation("ReviewLikes");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieTrackR.Domain.Entities.UserList", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
